### ISSUE TITLE
URLs are decoded when clicking on link

### ISSUE THREAD

**Issue by sladkoff** [Jaben/Papercut#4]
I was just testing emails where I send a URL with an encoded Base64 String in the query parameters. 
E.g: ``http://localhost:8080/test?key=NmAUEbNrjNz2kY33VYZvCuVlq4aA8PpA5%2BLOGQ8F72w%3D``

Notice the encoded **%2B (+)** and **%3D (=)**

When inspected in Papercut, the body of the email contains a link with the href parameter as stated above with escaped special characters.
When I *click* on the link inside Papercut though, it opens my browser at: 
``http://localhost:8080/test?key=NmAUEbNrjNz2kY33VYZvCuVlq4aA8PpA5+LOGQ8F72w=``
As you can see, the "+" and "=" have been URL-decoded. 

Is this the appropriate behavior or is it OK to report this is a bug?

**Comment by gnjack** [comment]
It looks like this is caused by using `Uri.ToString()` instead of `Uri.AbsoluteUri` in `MessageDetailHtmlViewModel.OnNavigating`:
https://github.com/Jaben/Papercut/blob/7f8ef8e7979621bd7b7a602ef0a4d384af75ff49/src/ViewModels/MessageDetailHtmlViewModel.cs#L100

See: http://code.logos.com/blog/2010/08/uritostring_must_die.html

I'm happy to submit a PR for this fix - it seems to work after a quick test locally.

**Comment by Jaben** [comment]
Wonderful.
